export const AUDIT_STATUS = {
    PENDING: "PENDING",
    REJECTED: "REJECTED",
    COMPLETED: "COMPLETED"
} as const;
export type AUDIT_STATUS = (typeof AUDIT_STATUS)[keyof typeof AUDIT_STATUS];
export const EVENT_TYPE = {
    ASSESSMENT_SUBMITTED: "ASSESSMENT_SUBMITTED",
    ASSESSMENT_REJECTED: "ASSESSMENT_REJECTED",
    ASSESSMENT_APPROVED: "ASSESSMENT_APPROVED",
    ASSESSMENT_COMPLETED: "ASSESSMENT_COMPLETED",
    EMAIL_SUPPLIER_CREATED: "EMAIL_SUPPLIER_CREATED",
    ASSESSMENT_DATA_DUE: "ASSESSMENT_DATA_DUE",
    AUDIT_COMPLETED: "AUDIT_COMPLETED",
    AUDIT_FAILED: "AUDIT_FAILED",
    FIRST_LOGIN: "FIRST_LOGIN",
    ASSESSMENT_RECURRENCE_CREATED: "ASSESSMENT_RECURRENCE_CREATED",
    AUDIT_DUE: "AUDIT_DUE",
    IN_PROGRESS: "IN_PROGRESS"
} as const;
export type EVENT_TYPE = (typeof EVENT_TYPE)[keyof typeof EVENT_TYPE];
export const NOTIFICATION_USER_TYPE = {
    AUDITOR: "AUDITOR",
    SPOC: "SPOC",
    CUSTOMER: "CUSTOMER"
} as const;
export type NOTIFICATION_USER_TYPE = (typeof NOTIFICATION_USER_TYPE)[keyof typeof NOTIFICATION_USER_TYPE];
export const JOB_STATUS = {
    SUCCESS: "SUCCESS",
    FAIL: "FAIL"
} as const;
export type JOB_STATUS = (typeof JOB_STATUS)[keyof typeof JOB_STATUS];
export const ASSESSMENT_QUESTION_STATUS = {
    DATA_INCOMPLETE: "DATA_INCOMPLETE",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED"
} as const;
export type ASSESSMENT_QUESTION_STATUS = (typeof ASSESSMENT_QUESTION_STATUS)[keyof typeof ASSESSMENT_QUESTION_STATUS];
export const LOCATION_TYPE = {
    GLOBAL: "GLOBAL",
    COUNTRY: "COUNTRY",
    LOCATION: "LOCATION"
} as const;
export type LOCATION_TYPE = (typeof LOCATION_TYPE)[keyof typeof LOCATION_TYPE];
export const REPORT_STATUS = {
    IN_PROGRESS: "IN_PROGRESS",
    IN_AUDIT: "IN_AUDIT",
    REJECTED: "REJECTED",
    COMPLETED: "COMPLETED"
} as const;
export type REPORT_STATUS = (typeof REPORT_STATUS)[keyof typeof REPORT_STATUS];
export const ASSIGNMENT_STATUS = {
    NONE: "NONE",
    COLLABORATION: "COLLABORATION",
    ASSIGNMENT: "ASSIGNMENT",
    LOCKED: "LOCKED"
} as const;
export type ASSIGNMENT_STATUS = (typeof ASSIGNMENT_STATUS)[keyof typeof ASSIGNMENT_STATUS];
export const QUESTION_APPROVAL_STATUS = {
    PENDING: "PENDING",
    REJECTED: "REJECTED",
    COMPLETED: "COMPLETED"
} as const;
export type QUESTION_APPROVAL_STATUS = (typeof QUESTION_APPROVAL_STATUS)[keyof typeof QUESTION_APPROVAL_STATUS];
export const QUESTION_TOPIC_TYPE = {
    NULL: "NULL",
    ESSENTIAL: "ESSENTIAL",
    LEADERSHIP: "LEADERSHIP"
} as const;
export type QUESTION_TOPIC_TYPE = (typeof QUESTION_TOPIC_TYPE)[keyof typeof QUESTION_TOPIC_TYPE];
export const REPORTING_PERIOD_TYPE = {
    FINANCIAL_YEAR: "FINANCIAL_YEAR",
    MONTH: "MONTH"
} as const;
export type REPORTING_PERIOD_TYPE = (typeof REPORTING_PERIOD_TYPE)[keyof typeof REPORTING_PERIOD_TYPE];
export const REPORTING_FREQUENCY = {
    YEARLY: "YEARLY",
    MONTHLY: "MONTHLY"
} as const;
export type REPORTING_FREQUENCY = (typeof REPORTING_FREQUENCY)[keyof typeof REPORTING_FREQUENCY];
export const ESG = {
    ENVIRONMENT: "ENVIRONMENT",
    SOCIAL: "SOCIAL",
    GOVERNANCE: "GOVERNANCE"
} as const;
export type ESG = (typeof ESG)[keyof typeof ESG];
